### ISSUE TITLE
something i missing here?

### ISSUE THREAD

**Issue by johnfelipe** [Aaron-Paul/Online-Medical-Consultant#1]
root@eh682214710:~/Online-Medical-Consultant/Main# set FLASK_APP=app.py
	root@eh682214710:~/Online-Medical-Consultant/Main# flask run --host=0.0.0.0
	 * Environment: production
	   WARNING: This is a development server. Do not use it in a production deployment.
	   Use a production WSGI server instead.
	 * Debug mode: off
	/usr/local/lib/python3.8/dist-packages/sklearn/base.py:313: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.23.1 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
	  warnings.warn(
	/usr/local/lib/python3.8/dist-packages/sklearn/base.py:313: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.23.1 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
	  warnings.warn(
	/usr/local/lib/python3.8/dist-packages/sklearn/base.py:313: UserWarning: Trying to unpickle estimator SVC from version 0.24.1 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
	  warnings.warn(
	/usr/local/lib/python3.8/dist-packages/sklearn/base.py:313: UserWarning: Trying to unpickle estimator SVC from version 0.23.2 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
	  warnings.warn(
	/usr/local/lib/python3.8/dist-packages/sklearn/base.py:313: UserWarning: Trying to unpickle estimator StandardScaler from version 0.23.2 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
	  warnings.warn(
	/usr/local/lib/python3.8/dist-packages/sklearn/base.py:313: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.24.0 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
	  warnings.warn(
	/usr/local/lib/python3.8/dist-packages/sklearn/base.py:313: UserWarning: Trying to unpickle estimator StandardScaler from version 0.24.0 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
	  warnings.warn(
	 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
	[2022-01-10 23:34:51,955] ERROR in app: Exception on / [GET]
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
		response = self.full_dispatch_request()
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
		rv = self.handle_user_exception(e)
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
		reraise(exc_type, exc_value, tb)
	  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
		raise value
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
		rv = self.dispatch_request()
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
		return self.view_functions[rule.endpoint](**req.view_args)
	  File "/usr/local/lib/python3.8/dist-packages/flask_cors/decorator.py", line 128, in wrapped_function
		resp = make_response(f(*args, **kwargs))
	  File "/root/Online-Medical-Consultant/Main/app.py", line 25, in home
		return render_template('home.html')
	  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 138, in render_template
		ctx.app.jinja_env.get_or_select_template(template_name_or_list),
	  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 930, in get_or_select_template
		return self.get_template(template_name_or_list, parent, globals)
	  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 883, in get_template
		return self._load_template(name, self.make_globals(globals))
	  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 857, in _load_template
		template = self.loader.load(self, name, globals)
	  File "/usr/local/lib/python3.8/dist-packages/jinja2/loaders.py", line 115, in load
		source, filename, uptodate = self.get_source(environment, name)
	  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 60, in get_source
		return self._get_source_fast(environment, template)
	  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 89, in _get_source_fast
		raise TemplateNotFound(template)
	jinja2.exceptions.TemplateNotFound: home.html
	200.118.204.70 - - [10/Jan/2022 23:34:51] "GET / HTTP/1.1" 500 -
	200.118.204.70 - - [10/Jan/2022 23:34:52] "GET /favicon.ico HTTP/1.1" 404 -
	[2022-01-10 23:34:54,380] ERROR in app: Exception on / [GET]
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
		response = self.full_dispatch_request()
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
		rv = self.handle_user_exception(e)
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
		reraise(exc_type, exc_value, tb)
	  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
		raise value
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
		rv = self.dispatch_request()
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
		return self.view_functions[rule.endpoint](**req.view_args)
	  File "/usr/local/lib/python3.8/dist-packages/flask_cors/decorator.py", line 128, in wrapped_function
		resp = make_response(f(*args, **kwargs))
	  File "/root/Online-Medical-Consultant/Main/app.py", line 25, in home
		return render_template('home.html')
	  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 138, in render_template
		ctx.app.jinja_env.get_or_select_template(template_name_or_list),
	  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 930, in get_or_select_template
		return self.get_template(template_name_or_list, parent, globals)
	  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 883, in get_template
		return self._load_template(name, self.make_globals(globals))
	  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 857, in _load_template
		template = self.loader.load(self, name, globals)
	  File "/usr/local/lib/python3.8/dist-packages/jinja2/loaders.py", line 115, in load
		source, filename, uptodate = self.get_source(environment, name)
	  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 60, in get_source
		return self._get_source_fast(environment, template)
	  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 89, in _get_source_fast
		raise TemplateNotFound(template)
	jinja2.exceptions.TemplateNotFound: home.html
	200.118.204.70 - - [10/Jan/2022 23:34:54] "GET / HTTP/1.1" 500 -

![SNAG-0869](https://user-images.githubusercontent.com/428820/148855472-74ac5631-d674-486b-9c41-3dab5c4f9301.png)

**Comment by johnfelipe** [comment]
root@eh68221471012:~/Online-Medical-Consultant/Main# python3 app.py
	/usr/local/lib/python3.8/dist-packages/sklearn/base.py:313: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.23.1 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
	  warnings.warn(
	/usr/local/lib/python3.8/dist-packages/sklearn/base.py:313: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.23.1 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
	  warnings.warn(
	/usr/local/lib/python3.8/dist-packages/sklearn/base.py:313: UserWarning: Trying to unpickle estimator SVC from version 0.24.1 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
	  warnings.warn(
	/usr/local/lib/python3.8/dist-packages/sklearn/base.py:313: UserWarning: Trying to unpickle estimator SVC from version 0.23.2 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
	  warnings.warn(
	/usr/local/lib/python3.8/dist-packages/sklearn/base.py:313: UserWarning: Trying to unpickle estimator StandardScaler from version 0.23.2 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
	  warnings.warn(
	/usr/local/lib/python3.8/dist-packages/sklearn/base.py:313: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.24.0 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
	  warnings.warn(
	/usr/local/lib/python3.8/dist-packages/sklearn/base.py:313: UserWarning: Trying to unpickle estimator StandardScaler from version 0.24.0 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
	  warnings.warn(
	 * Serving Flask app "app" (lazy loading)
	 * Environment: production
	   WARNING: This is a development server. Do not use it in a production deployment.
	   Use a production WSGI server instead.
	 * Debug mode: off
	 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
	[2022-01-11 04:29:29,729] ERROR in app: Exception on / [GET]
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
		response = self.full_dispatch_request()
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
		rv = self.handle_user_exception(e)
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
		reraise(exc_type, exc_value, tb)
	  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
		raise value
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
		rv = self.dispatch_request()
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
		return self.view_functions[rule.endpoint](**req.view_args)
	  File "/usr/local/lib/python3.8/dist-packages/flask_cors/decorator.py", line 128, in wrapped_function
		resp = make_response(f(*args, **kwargs))
	  File "app.py", line 25, in home
		return render_template('home.html')
	  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 138, in render_template
		ctx.app.jinja_env.get_or_select_template(template_name_or_list),
	  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 930, in get_or_select_template
		return self.get_template(template_name_or_list, parent, globals)
	  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 883, in get_template
		return self._load_template(name, self.make_globals(globals))
	  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 857, in _load_template
		template = self.loader.load(self, name, globals)
	  File "/usr/local/lib/python3.8/dist-packages/jinja2/loaders.py", line 115, in load
		source, filename, uptodate = self.get_source(environment, name)
	  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 60, in get_source
		return self._get_source_fast(environment, template)
	  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 89, in _get_source_fast
		raise TemplateNotFound(template)
	jinja2.exceptions.TemplateNotFound: home.html
	200.118.204.70 - - [11/Jan/2022 04:29:29] "GET / HTTP/1.1" 500 -
	[2022-01-11 04:29:31,441] ERROR in app: Exception on / [GET]
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
		response = self.full_dispatch_request()
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
		rv = self.handle_user_exception(e)
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
		reraise(exc_type, exc_value, tb)
	  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
		raise value
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
		rv = self.dispatch_request()
	  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
		return self.view_functions[rule.endpoint](**req.view_args)
	  File "/usr/local/lib/python3.8/dist-packages/flask_cors/decorator.py", line 128, in wrapped_function
		resp = make_response(f(*args, **kwargs))
	  File "app.py", line 25, in home
		return render_template('home.html')
	  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 138, in render_template
		ctx.app.jinja_env.get_or_select_template(template_name_or_list),
	  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 930, in get_or_select_template
		return self.get_template(template_name_or_list, parent, globals)
	  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 883, in get_template
		return self._load_template(name, self.make_globals(globals))
	  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 857, in _load_template
		template = self.loader.load(self, name, globals)
	  File "/usr/local/lib/python3.8/dist-packages/jinja2/loaders.py", line 115, in load
		source, filename, uptodate = self.get_source(environment, name)
	  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 60, in get_source
		return self._get_source_fast(environment, template)
	  File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 89, in _get_source_fast
		raise TemplateNotFound(template)
	jinja2.exceptions.TemplateNotFound: home.html
	200.118.204.70 - - [11/Jan/2022 04:29:31] "GET / HTTP/1.1" 500 -

still issues here,, pls help
